/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customInstance } from "./axios-client";
export interface BodyPredictPredictPost {
  input: Blob;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface PredictOutput {
  label: string;
  probability_blight: number;
  probability_common_rust: number;
  probability_gray_leaf_spot: number;
  probability_healthy: number;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type HealthCheckHealthGet200 = { [key: string]: unknown };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getFastAPI = () => {
  /**
   * @summary Predict
   */
  const predictPredictPost = (
    bodyPredictPredictPost: BodyPredictPredictPost,
    options?: SecondParameter<typeof customInstance<PredictOutput>>,
  ) => {
    const formData = new FormData();
    formData.append(`input`, bodyPredictPredictPost.input);

    return customInstance<PredictOutput>(
      {
        url: `/predict`,
        method: "POST",
        headers: { "Content-Type": "multipart/form-data" },
        data: formData,
      },
      options,
    );
  };

  /**
   * @summary Health Check
   */
  const healthCheckHealthGet = (
    options?: SecondParameter<typeof customInstance<HealthCheckHealthGet200>>,
  ) => {
    return customInstance<HealthCheckHealthGet200>(
      { url: `/health`, method: "GET" },
      options,
    );
  };

  return { predictPredictPost, healthCheckHealthGet };
};
export type PredictPredictPostResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFastAPI>["predictPredictPost"]>>
>;
export type HealthCheckHealthGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFastAPI>["healthCheckHealthGet"]>>
>;
